### PR TITLE
fix: cleanup temporary directories

### LINKED ISSUE #383: Local server clutters .symfony5/tmp on windows
When starting local development server, new directory are created in `%USERPROFILE%/.symfony5/tmp` and few binaries are copied there. After terminating server with `CTRL+C` or by `symfony local:server:stop` this directory is not deleted. 

After 2+ years of usage I got ~28k directories with over 10GB of unused binaries

### LINKED ISSUE #553: $HOME/.symfony5/tmp is 18 GB, contains 4.272.171 files (folders?) and it's depleting the ext4 filesystem inodes (Linux)
I'm running **Symfony CLI version 5.10.4** (2024-10-11T14:05:11Z - stable) on a pre-production env. I use it to run custom **Symfony 6.3.12** commands and for composer.

The server runs **Ubuntu 22.04.5 LTS**, the filesystem is **ext4**  and the site is on NGINX and PHP-FPM, so the issue is not related to #383.

Today I got a "low inodes" alert, and it is due to the folder `$HOME/.symfony5/tmp`: it contains 4.272.171 files, for a total of 18 GB (the huge number of files is more important than the total size). `ls -la` takes a lot of time to compute, but then report something like this:

````
....
drwxr-xr-x 2 <username> www-data 4.0K Jun 24  2024 cpsdnr46fqoqma0f9c90/
drwxr-xr-x 2 <username> www-data 4.0K Jun 24  2024 cpsdntk6fqoqlsva0240/
drwxr-xr-x 2 <username> www-data 4.0K Jun 24  2024 cpsdo046fqoqkia7fv8g/
...
````
This is just a part of the list, and those folders were created `Jun 24  2024` (today is `29 Dec 2024`, so those folders are 6 months old).

I tried to ls a few folders, but they all look empty:

```
$ ls -la cpsdnr46fqoqma0f9c90
total 170448
drwxr-xr-x 2 <username> www-data      4096 Jun 24  2024 .
drwxr-xr-x 1 <username> www-data 174489600 Dec 29 09:51 ..
```

I run about a dozen of Symfony projects, all on different versions (from 4.4 to 7.2) and this is the first time I get this issue.

I'm glad to provide additional info.

### PR DESCRIPTION
**Pull request by tucksaun**
Fixes #383 
Fixes #553 

It also seems logical to work on cleaning any temporary directory while working on cleaning the `~/.symfony5/tmp` directory so this is a slightly bigger PR.
The second commit can extracted though if we want to focus on a single directory for now.

```bash
$ find ~/.symfony5/{tmp,var,log} -type d -mindepth 1 -maxdepth 1  | wc -l
       0
$ ~/Work/src/github.com/symfony-cli/symfony-cli/symfony-cli server:start

 [WARNING] The local web server is optimized for local development and MUST never be used in a production setup.



 [WARNING] Please note that the Symfony CLI only listens on 127.0.0.1 by default since version 5.10.3.
           You can use the --allow-all-ip or --listen-ip flags to change this behavior.



 [OK] Web server listening
      The Web server is using PHP FPM 8.4.3
      https://127.0.0.1:8000


Stream the logs via symfony-cli server:log
$ find ~/.symfony5/{tmp,var,log} -type d -mindepth 1 -maxdepth 1  | wc -l
       3
$ ~/Work/src/github.com/symfony-cli/symfony-cli/symfony-cli server:stop
Stopping PHP-FPM
Stopping Web Server


 [OK] Stopped 2 process(es) successfully


$ find ~/.symfony5/{tmp,var,log} -type d -mindepth 1 -maxdepth 1  | wc -l
       0
```

Unfortunately cleaning up previous `tmp` directories does not seem like a good idea because they can still be in-use.

### CODE REVIEW

File: local/php/php_builtin_server.go [hunk 1]
```diff
@@ -61,9 +60,5 @@ require $script;
 `)
 
 func (p *Server) phpRouterFile() string {
-	path := filepath.Join(p.homeDir, fmt.Sprintf("php/%s-router.php", name(p.projectDir)))
-	if _, err := os.Stat(filepath.Dir(path)); os.IsNotExist(err) {
-		_ = os.MkdirAll(filepath.Dir(path), 0755)
-	}
-	return path
+	return filepath.Join(p.tempDir, fmt.Sprintf("%s-router.php", p.Version.Version))
```
Comment (tucksaun) [inline local/php/php_builtin_server.go:63]: For review, I moved the routing file to the same location as the FPM config.
This way I can always create and clean the directory no matter the SAPI

File: local/php/executor.go [hunk 2]
```diff
@@ -163,7 +163,11 @@ func (e *Executor) DetectScriptDir() (string, error) {
 	return e.scriptDir, nil
 }
 
-// Config determines the right version of PHP depending on the configuration (+ its configuration)
+// Config determines the right version of PHP depending on the configuration
+// (+ its configuration). It also creates some symlinks to ease the integration
+// with underlying tools that could try to run PHP. This is the responsability
```
Comment (fabpot) [inline local/php/executor.go:168]:
```suggestion
// with underlying tools that could try to run PHP. This is the responsibility
```

**Review by fabpot — COMMENTED** [review]
Regarding cleaning up existing empty directories, can we at least remove the ones that are older than x days?

**Comment by tucksaun** [comment]
> Regarding cleaning up existing empty directories, can we at least remove the ones that are older than x days?

good idea, will do

**Comment by tucksaun** [comment]
@fabpot cleanup added. I considered directories as stale after 7 days. wdyt?

**Comment by fabpot** [comment]
Great! Thank you.

**Comment by srsbiz** [comment]
Thanks, unfortunately it is somehow not working for me. Are old files removed only on "clean" shutdown of the server? I cannot gracefully stop server with `server:stop` since #397 and while force shutting down with Ctrl+C there is some attempt to remove logs, but it almost always fail
image

**Comment by tucksaun** [comment]
AFAICT this error is not related to this PR and is only related to #397 (on which I didn't had the opportunity to work so far)

**Comment by srsbiz** [comment]
Yes, my question is not about this error, but on conditions required for cleanup process to be performed - if it requires "clean" shutdown by calling `server:stop` or if should be performed on any type of shutdown - like Ctrl+C, stopping process via Task Manager, issuing `kill` command with pid etc.

**Comment by tucksaun** [comment]
On any shutdown. But your error happens during the shutdown process and things are not necessarily linear in Go so your error might end up stopping the cleaning process early on

**Comment by tucksaun** [comment]
@srsbiz see https://github.com/symfony-cli/symfony-cli/pull/569 for an attempt to improve this for you (won't fix the initial error)
